### PR TITLE
Plates, Ropes, Carrots, Boxes

### PR DESCRIPTION
**Pull request by hjsuh94**
Addition of examples for plates, ropes, and carrots. 

Also fixes the default argument to be compatible with python 3.6 - hopefully this should run fine in 3.7 and further as well?

---
This change is [Reviewable](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/1)

### CODE REVIEW

**Review by pangtao22 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/1)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @hjsuh94)

___
*[core/quasistatic_simulator.py, line 74 at r1](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/1#-Mh5Zzb43OhUSlxBp2JX:-Mh5Zzb43OhUSlxBp2JY:b-1boy29) ([raw file](https://github.com/pangtao22/quasistatic_simulator/blob/bdb9277435aea8baf69905e6f3a9995b3245fa22/core/quasistatic_simulator.py#L74)):*
> ```Python
>         "is_quasi_dynamic", "mode", "log_barrier_weight", "requires_grad"
>         ])
> QuasistaticSimParameters.__new__.__defaults__ = (
> ```

We could use something likes [this](https://flaviocopes.com/python-check-version/) to check the current python version, and deal with default parameters depending on the current python version.
___
*[examples/carrots/run_carrots.py, line 30 at r1](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/1#-Mh5_wZuEvXiqNTIWfCA:-Mh5_wZuEvXiqNTIWfCB:bxl6v62) ([raw file](https://github.com/pangtao22/quasistatic_simulator/blob/bdb9277435aea8baf69905e6f3a9995b3245fa22/examples/carrots/run_carrots.py#L30)):*
> ```Python
> # object
> num_pieces = 100
> object_sdf_dict = {}
> ```

nit: comprehension can be used here to shorten the code. 
___
*[examples/plate_pickup/create_plate_sdf.py, line 31 at r1](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/1#-Mh5_N-W9Z5f9HWFR7Ln:-Mh5_N-W9Z5f9HWFR7Lo:b-mb9bso) ([raw file](https://github.com/pangtao22/quasistatic_simulator/blob/bdb9277435aea8baf69905e6f3a9995b3245fa22/examples/plate_pickup/create_plate_sdf.py#L31)):*
> ```Python
> # 1. Initialize the file.
> 
> f = open("models/plate.sdf", 'w')
> ```

There is a nice python library called `lxml` that facilitates generating sdf files programmatically. I heard about it from Greg, and there's an example of using the library here: https://github.com/pangtao22/pick_and_place_benchmarking_framework/blob/hydroelastic_contact/box_sdf_generation.py . We can merge the current version for now and leave the refactoring to a future PR.

**Review by hjsuh94 — COMMENTED** [review]
Addressed comments and added examples for box pushing and pivoting. 

> *[Reviewable](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/1#-:-MhG3nZR0BtwSLBsAiMj:by12q2b)* status: 0 of 22 files reviewed, 2 unresolved discussions (waiting on @pangtao22)

___
*[core/quasistatic_simulator.py, line 74 at r1](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/1#-Mh5Zzb43OhUSlxBp2JX:-MhG3ifh1yzPKnmLZurk:b-7rl0jd) ([raw file](https://github.com/pangtao22/quasistatic_simulator/blob/bdb9277435aea8baf69905e6f3a9995b3245fa22/core/quasistatic_simulator.py#L74)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

We could use something likes [this](https://flaviocopes.com/python-check-version/) to check the current python version, and deal with default parameters depending on the current python version.
</blockquote></details>

done.
___
*[examples/carrots/run_carrots.py, line 30 at r1](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/1#-Mh5_wZuEvXiqNTIWfCA:-MhG3hk4-8lM9QKHFMkq:b-7rl0jd) ([raw file](https://github.com/pangtao22/quasistatic_simulator/blob/bdb9277435aea8baf69905e6f3a9995b3245fa22/examples/carrots/run_carrots.py#L30)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

nit: comprehension can be used here to shorten the code. 
</blockquote></details>

done.
___
*[examples/plate_pickup/create_plate_sdf.py, line 31 at r1](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/1#-Mh5_N-W9Z5f9HWFR7Ln:-MhG3jqOBQJpVFOxZ5NN:bf5bwgz) ([raw file](https://github.com/pangtao22/quasistatic_simulator/blob/bdb9277435aea8baf69905e6f3a9995b3245fa22/examples/plate_pickup/create_plate_sdf.py#L31)):*
<details><summary><i>Previously, pangtao22 wrote…</i></summary><blockquote>

There is a nice python library called `lxml` that facilitates generating sdf files programmatically. I heard about it from Greg, and there's an example of using the library here: https://github.com/pangtao22/pick_and_place_benchmarking_framework/blob/hydroelastic_contact/box_sdf_generation.py . We can merge the current version for now and leave the refactoring to a future PR.
</blockquote></details>

Sounds good! Manual generation was a bit painful :sweat:

**Review by pangtao22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/1)* status: 0 of 22 files reviewed, 2 unresolved discussions (waiting on @pangtao22)

___
*[-- commits, line 1 at r2](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/1#-MhGXcL52tN37d60h787:-MhGXcL52tN37d60h788:blie934) ([raw file](https://github.com/pangtao22/quasistatic_simulator/blob/57cbdcd7da9151b2253dfe60b3ede5ada67aa995/-- commits#L1)):*
Not sure what this file is... but we can merge it and see if it causes any trouble

**Review by pangtao22 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/1#-:-MhGXk7r5TsRreCF5ZtV:bg7igkv)* status: 0 of 22 files reviewed, 2 unresolved discussions (waiting on @pangtao22)

**Pull request merged**
